// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OyoLife.Data;

namespace OyoLife.Migrations
{
    [DbContext(typeof(OyoLifeContext))]
    partial class OyoLifeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OyoLife.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("OyoLife.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Booking_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PGID")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PGID");

                    b.HasIndex("UserId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("OyoLife.Models.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Dealer_AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Dealer_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dealer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dealer_PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Dealer_AddressId");

                    b.ToTable("Dealer");
                });

            modelBuilder.Entity("OyoLife.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Facility_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PGId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PGId");

                    b.ToTable("Facility");
                });

            modelBuilder.Entity("OyoLife.Models.PG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About_Pg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<int?>("Pg_AdressId")
                        .HasColumnType("int");

                    b.Property<string>("Pg_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pg_Name")
                        .HasColumnType("int");

                    b.Property<double>("Pg_Price")
                        .HasColumnType("float");

                    b.Property<string>("Pg_Sharing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pg_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("Pg_AdressId");

                    b.ToTable("PG");
                });

            modelBuilder.Entity("OyoLife.Models.PgImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PGId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PGId");

                    b.ToTable("PgImage");
                });

            modelBuilder.Entity("OyoLife.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_age")
                        .HasColumnType("int");

                    b.Property<string>("user_gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("OyoLife.Models.Booking", b =>
                {
                    b.HasOne("OyoLife.Models.PG", "PG")
                        .WithMany()
                        .HasForeignKey("PGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OyoLife.Models.User", null)
                        .WithMany("Bookings")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("OyoLife.Models.Dealer", b =>
                {
                    b.HasOne("OyoLife.Models.Address", "Dealer_Address")
                        .WithMany()
                        .HasForeignKey("Dealer_AddressId");
                });

            modelBuilder.Entity("OyoLife.Models.Facility", b =>
                {
                    b.HasOne("OyoLife.Models.PG", null)
                        .WithMany("Pg_Facilites")
                        .HasForeignKey("PGId");
                });

            modelBuilder.Entity("OyoLife.Models.PG", b =>
                {
                    b.HasOne("OyoLife.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OyoLife.Models.Address", "Pg_Adress")
                        .WithMany()
                        .HasForeignKey("Pg_AdressId");
                });

            modelBuilder.Entity("OyoLife.Models.PgImage", b =>
                {
                    b.HasOne("OyoLife.Models.PG", null)
                        .WithMany("Pg_Images")
                        .HasForeignKey("PGId");
                });
#pragma warning restore 612, 618
        }
    }
}
